export const wordPhrases = {
  Angry: 'I am angry',
  Bad: 'That is bad',
  Brother: 'my brother',
  Call: 'Please call',
  Cold: 'I feel cold',
  Come: 'Please come',
  Doctor: 'I need a doctor',
  Drink: 'I want to drink',
  Eat: 'I want to eat',
  Father: 'my father',
  Finish: 'I am finished',
  Friend: 'my friend',
  Go: 'I want to go',
  Good: 'That is good',
  Happy: 'I am happy',
  Hello: 'Hello',
  Help: 'I need help',
  Home: 'I want to go home',
  Hospital: 'I need to go to the hospital',
  Hot: 'I feel hot',
  How: 'How',
  Hungry: 'I am hungry',
  Me: 'Me',
  Medicine: 'I need medicine',
  More: 'I want more',
  Mother: 'my mother',
  No: 'No',
  Pain: 'I am in pain',
  Please: 'Please',
  Sad: 'I am sad',
  Scared: 'I am scared',
  Sister: 'my sister',
  Sit: 'Please sit',
  Sorry: 'I am sorry',
  Stand: 'Please stand',
  Stop: 'Please stop',
  ThankYou: 'Thank you',
  Tired: 'I am tired',
  Toilet: 'I need the toilet',
  Wait: 'Please wait',
  Water: 'I want water',
  What: 'What',
  Where: 'Where',
  Yes: 'Yes',
  You: 'You',
}